"use server";
import { revalidatePath } from "next/cache";
import { changeManagedSubscriptionStatus, createManagedSubscription, createPlan, createPlanRevision, generateBillingCycles, type PlanPeriodicity } from "@/lib/services/plan.service";
type State = { error?: string; success?: boolean; message?: string };
export async function createPlanAction(_s: State, f: FormData): Promise<State> { const r = await createPlan({ name:String(f.get("name")??""),description:String(f.get("description")??""),amountCents:Math.round(Number(f.get("amount")??0)*100),periodicity:String(f.get("periodicity")??"") as PlanPeriodicity,dueDay:Number(f.get("dueDay")??0),effectiveFrom:String(f.get("effectiveFrom")??"") }); if("error" in r)return r; revalidatePath("/socio/financeiro"); return r; }
export async function createManagedSubscriptionAction(_s: State, f: FormData): Promise<State> { const r = await createManagedSubscription({studentId:String(f.get("studentId")??""),enrollmentId:String(f.get("enrollmentId")??""),planVersionId:String(f.get("planVersionId")??""),startsOn:String(f.get("startsOn")??"")}); if("error" in r)return r; revalidatePath("/socio/financeiro"); return r; }
export async function createPlanRevisionAction(_s: State, f: FormData): Promise<State> { const r = await createPlanRevision({planId:String(f.get("planId")??""),amountCents:Math.round(Number(f.get("amount")??0)*100),periodicity:String(f.get("periodicity")??"") as PlanPeriodicity,dueDay:Number(f.get("dueDay")??0),effectiveFrom:String(f.get("effectiveFrom")??"")}); if("error" in r)return r; revalidatePath("/socio/financeiro"); return r; }
export async function generateBillingCyclesAction(_s: State, f: FormData): Promise<State> { const r = await generateBillingCycles({windowStartsOn:String(f.get("windowStartsOn")??""),windowEndsOn:String(f.get("windowEndsOn")??"")}); if("error" in r)return r; revalidatePath("/socio/financeiro"); return { success:true, message:`${r.generatedCount} cobrança(s) criada(s).` }; }
export async function changeSubscriptionStatusAction(_s: State, f: FormData): Promise<State> { const r = await changeManagedSubscriptionStatus({subscriptionId:String(f.get("subscriptionId")??""),status:String(f.get("status")??"") as "active"|"paused"|"ended"|"canceled"|"exempt",effectiveOn:String(f.get("effectiveOn")??""),reason:String(f.get("reason")??"")}); if("error" in r)return r; revalidatePath("/socio/financeiro"); return r; }
