"use server";
import { revalidatePath } from "next/cache";
import { requireRole } from "@/lib/auth/session";
import { createSubscription, markChargePaid, updateSubscriptionStatus } from "@/lib/services/financial.service";
import { createSubscriptionSchema, markChargePaidSchema, updateSubscriptionStatusSchema } from "@/lib/validators/financial";
import type { TrainingActionState } from "./training.state";
import { assertLegacyFinancialMutationAllowed } from "@/lib/environment/external-effects-policy";
export async function createSubscriptionAction(_: TrainingActionState, formData: FormData): Promise<TrainingActionState> { assertLegacyFinancialMutationAllowed(); const parsed = createSubscriptionSchema.safeParse({ athleteId: formData.get("athleteId"), amountCents: formData.get("amountCents"), periodicity: formData.get("periodicity"), dueDay: formData.get("dueDay"), paymentMethod: formData.get("paymentMethod") || undefined, status: formData.get("status"), startDate: formData.get("startDate") }); if (!parsed.success) return { fieldErrors: parsed.error.flatten().fieldErrors }; const result = await createSubscription(await requireRole("treinador"), parsed.data); if ("error" in result) return { error: result.error }; revalidatePath("/treinador/financeiro"); revalidatePath("/treinador"); return { success: "Assinatura e primeira cobrança criadas." }; }
export async function markChargePaidAction(_: TrainingActionState, formData: FormData): Promise<TrainingActionState> { assertLegacyFinancialMutationAllowed(); const parsed = markChargePaidSchema.safeParse({ chargeId: formData.get("chargeId") }); if (!parsed.success) return { fieldErrors: parsed.error.flatten().fieldErrors }; const result = await markChargePaid(await requireRole("treinador"), parsed.data.chargeId); if ("error" in result) return { error: result.error }; revalidatePath("/treinador/financeiro"); revalidatePath("/treinador"); return { success: "Pagamento registrado." }; }
export async function updateSubscriptionStatusAction(_: TrainingActionState, formData: FormData): Promise<TrainingActionState> { assertLegacyFinancialMutationAllowed(); const parsed = updateSubscriptionStatusSchema.safeParse({ subscriptionId: formData.get("subscriptionId"), status: formData.get("status") }); if (!parsed.success) return { fieldErrors: parsed.error.flatten().fieldErrors }; const result = await updateSubscriptionStatus(await requireRole("treinador"), parsed.data); if ("error" in result) return { error: result.error }; revalidatePath("/treinador/financeiro"); revalidatePath("/treinador"); return { success: "Situação da assinatura atualizada." }; }
