// Generated by scripts/generate-mvp-foundation-types.mjs. Do not edit manually.
export type MvpJson = string | number | boolean | null | { [key: string]: MvpJson | undefined } | MvpJson[]

export type MvpEnums = {
  team_member_role: "socio" | "professor"
  team_member_status: "active" | "inactive"
  enrollment_status: "active" | "suspended" | "ended"
  attendance_status: "present" | "absent" | "excused" | "not_recorded"
  subscription_status: "draft" | "active" | "paused" | "ended" | "canceled" | "exempt"
  charge_status: "draft" | "open" | "overdue" | "paid" | "reversed" | "canceled" | "exempt"
  checkout_status: "created" | "active" | "paid" | "expired" | "canceled" | "failed"
  payment_status: "pending" | "authorized" | "confirmed" | "failed" | "canceled"
  settlement_status: "pending" | "received" | "reversed"
  refund_status: "requested" | "confirmed" | "reversed" | "failed" | "canceled"
  dispute_status: "open" | "under_review" | "won" | "lost" | "reversed" | "canceled"
  expense_status: "planned" | "paid" | "canceled"
  provider_event_status: "received" | "processing" | "processed" | "retryable_failure" | "dead_letter" | "ignored"
  message_status: "queued" | "claimed" | "submitted" | "delivered" | "read" | "retryable_failure" | "canceled" | "dead_letter"
  lead_status: "new" | "contacted" | "trial_scheduled" | "converted" | "closed"
}

export const MvpEnumConstants = {
  team_member_role: ["socio", "professor"],
  team_member_status: ["active", "inactive"],
  enrollment_status: ["active", "suspended", "ended"],
  attendance_status: ["present", "absent", "excused", "not_recorded"],
  subscription_status: ["draft", "active", "paused", "ended", "canceled", "exempt"],
  charge_status: ["draft", "open", "overdue", "paid", "reversed", "canceled", "exempt"],
  checkout_status: ["created", "active", "paid", "expired", "canceled", "failed"],
  payment_status: ["pending", "authorized", "confirmed", "failed", "canceled"],
  settlement_status: ["pending", "received", "reversed"],
  refund_status: ["requested", "confirmed", "reversed", "failed", "canceled"],
  dispute_status: ["open", "under_review", "won", "lost", "reversed", "canceled"],
  expense_status: ["planned", "paid", "canceled"],
  provider_event_status: ["received", "processing", "processed", "retryable_failure", "dead_letter", "ignored"],
  message_status: ["queued", "claimed", "submitted", "delivered", "read", "retryable_failure", "canceled", "dead_letter"],
  lead_status: ["new", "contacted", "trial_scheduled", "converted", "closed"],
} as const

export type MvpTables = {
  team_members: {
    Row: {
      id: string | null
      assessoria_id: string
      profile_id: string
      role: MvpEnums["team_member_role"]
      status: MvpEnums["team_member_status"]
      activated_at: string
      deactivated_at: string | null
      created_at: string
      updated_at: string
    }
    Insert: {
      id?: string | null
      assessoria_id: string
      profile_id: string
      role: MvpEnums["team_member_role"]
      status?: MvpEnums["team_member_status"]
      activated_at?: string
      deactivated_at?: string | null
      created_at?: string
      updated_at?: string
    }
    Update: {
      id?: string | null
      assessoria_id?: string
      profile_id?: string
      role?: MvpEnums["team_member_role"]
      status?: MvpEnums["team_member_status"]
      activated_at?: string
      deactivated_at?: string | null
      created_at?: string
      updated_at?: string
    }
    Relationships: [
      {
        foreignKeyName: "team_members_assessoria_id_fkey_12"
        columns: ["assessoria_id"]
        isOneToOne: false
        referencedRelation: "assessorias"
        referencedColumns: ["id"]
      },
      {
        foreignKeyName: "team_members_assessoria_id_profile_id_fkey_13"
        columns: ["assessoria_id", "profile_id"]
        isOneToOne: false
        referencedRelation: "profiles"
        referencedColumns: ["assessoria_id", "id"]
      },
    ]
  }
  students: {
    Row: {
      id: string | null
      assessoria_id: string
      auth_user_id: string | null
      legacy_atleta_id: string | null
      name: string
      email: string | null
      phone: string | null
      birth_date: string | null
      notes: string | null
      created_at: string
      updated_at: string
    }
    Insert: {
      id?: string | null
      assessoria_id: string
      auth_user_id?: string | null
      legacy_atleta_id?: string | null
      name: string
      email?: string | null
      phone?: string | null
      birth_date?: string | null
      notes?: string | null
      created_at?: string
      updated_at?: string
    }
    Update: {
      id?: string | null
      assessoria_id?: string
      auth_user_id?: string | null
      legacy_atleta_id?: string | null
      name?: string
      email?: string | null
      phone?: string | null
      birth_date?: string | null
      notes?: string | null
      created_at?: string
      updated_at?: string
    }
    Relationships: [
      {
        foreignKeyName: "students_assessoria_id_fkey_13"
        columns: ["assessoria_id"]
        isOneToOne: false
        referencedRelation: "assessorias"
        referencedColumns: ["id"]
      },
      {
        foreignKeyName: "students_assessoria_id_legacy_atleta_id_fkey_15"
        columns: ["assessoria_id", "legacy_atleta_id"]
        isOneToOne: false
        referencedRelation: "atletas"
        referencedColumns: ["assessoria_id", "id"]
      },
    ]
  }
  enrollments: {
    Row: {
      id: string | null
      assessoria_id: string
      student_id: string
      status: MvpEnums["enrollment_status"]
      starts_on: string
      ends_on: string | null
      suspension_reason: string | null
      created_at: string
      updated_at: string
    }
    Insert: {
      id?: string | null
      assessoria_id: string
      student_id: string
      status?: MvpEnums["enrollment_status"]
      starts_on: string
      ends_on?: string | null
      suspension_reason?: string | null
      created_at?: string
      updated_at?: string
    }
    Update: {
      id?: string | null
      assessoria_id?: string
      student_id?: string
      status?: MvpEnums["enrollment_status"]
      starts_on?: string
      ends_on?: string | null
      suspension_reason?: string | null
      created_at?: string
      updated_at?: string
    }
    Relationships: [
      {
        foreignKeyName: "enrollments_assessoria_id_student_id_fkey_11"
        columns: ["assessoria_id", "student_id"]
        isOneToOne: false
        referencedRelation: "students"
        referencedColumns: ["assessoria_id", "id"]
      },
    ]
  }
  enrollment_history: {
    Row: {
      id: string | null
      assessoria_id: string
      enrollment_id: string
      previous_status: MvpEnums["enrollment_status"] | null
      new_status: MvpEnums["enrollment_status"]
      actor_team_member_id: string | null
      reason: string | null
      occurred_at: string
      created_at: string
    }
    Insert: {
      id?: string | null
      assessoria_id: string
      enrollment_id: string
      previous_status?: MvpEnums["enrollment_status"] | null
      new_status: MvpEnums["enrollment_status"]
      actor_team_member_id?: string | null
      reason?: string | null
      occurred_at?: string
      created_at?: string
    }
    Update: {
      id?: string | null
      assessoria_id?: string
      enrollment_id?: string
      previous_status?: MvpEnums["enrollment_status"] | null
      new_status?: MvpEnums["enrollment_status"]
      actor_team_member_id?: string | null
      reason?: string | null
      occurred_at?: string
      created_at?: string
    }
    Relationships: [
      {
        foreignKeyName: "enrollment_history_assessoria_id_enrollment_id_fkey_10"
        columns: ["assessoria_id", "enrollment_id"]
        isOneToOne: false
        referencedRelation: "enrollments"
        referencedColumns: ["assessoria_id", "id"]
      },
      {
        foreignKeyName: "enrollment_history_assessoria_id_actor_team_member_id_fkey_11"
        columns: ["assessoria_id", "actor_team_member_id"]
        isOneToOne: false
        referencedRelation: "team_members"
        referencedColumns: ["assessoria_id", "id"]
      },
    ]
  }
  classes: {
    Row: {
      id: string | null
      assessoria_id: string
      name: string
      description: string | null
      active: boolean
      timezone: string
      created_at: string
      updated_at: string
    }
    Insert: {
      id?: string | null
      assessoria_id: string
      name: string
      description?: string | null
      active?: boolean
      timezone?: string
      created_at?: string
      updated_at?: string
    }
    Update: {
      id?: string | null
      assessoria_id?: string
      name?: string
      description?: string | null
      active?: boolean
      timezone?: string
      created_at?: string
      updated_at?: string
    }
    Relationships: [
      {
        foreignKeyName: "classes_assessoria_id_fkey_10"
        columns: ["assessoria_id"]
        isOneToOne: false
        referencedRelation: "assessorias"
        referencedColumns: ["id"]
      },
    ]
  }
  class_memberships: {
    Row: {
      id: string | null
      assessoria_id: string
      class_id: string
      student_id: string
      enrollment_id: string
      starts_on: string
      ends_on: string | null
      created_at: string
      updated_at: string
    }
    Insert: {
      id?: string | null
      assessoria_id: string
      class_id: string
      student_id: string
      enrollment_id: string
      starts_on: string
      ends_on?: string | null
      created_at?: string
      updated_at?: string
    }
    Update: {
      id?: string | null
      assessoria_id?: string
      class_id?: string
      student_id?: string
      enrollment_id?: string
      starts_on?: string
      ends_on?: string | null
      created_at?: string
      updated_at?: string
    }
    Relationships: [
      {
        foreignKeyName: "class_memberships_assessoria_id_class_id_fkey_11"
        columns: ["assessoria_id", "class_id"]
        isOneToOne: false
        referencedRelation: "classes"
        referencedColumns: ["assessoria_id", "id"]
      },
      {
        foreignKeyName: "class_memberships_assessoria_id_student_id_fkey_12"
        columns: ["assessoria_id", "student_id"]
        isOneToOne: false
        referencedRelation: "students"
        referencedColumns: ["assessoria_id", "id"]
      },
      {
        foreignKeyName: "class_memberships_assessoria_id_student_id_enrollment_id_fkey_13"
        columns: ["assessoria_id", "student_id", "enrollment_id"]
        isOneToOne: false
        referencedRelation: "enrollments"
        referencedColumns: ["assessoria_id", "student_id", "id"]
      },
    ]
  }
  class_meetings: {
    Row: {
      id: string | null
      assessoria_id: string
      class_id: string
      starts_at: string
      ends_at: string
      canceled_at: string | null
      cancellation_reason: string | null
      created_at: string
      updated_at: string
    }
    Insert: {
      id?: string | null
      assessoria_id: string
      class_id: string
      starts_at: string
      ends_at: string
      canceled_at?: string | null
      cancellation_reason?: string | null
      created_at?: string
      updated_at?: string
    }
    Update: {
      id?: string | null
      assessoria_id?: string
      class_id?: string
      starts_at?: string
      ends_at?: string
      canceled_at?: string | null
      cancellation_reason?: string | null
      created_at?: string
      updated_at?: string
    }
    Relationships: [
      {
        foreignKeyName: "class_meetings_assessoria_id_class_id_fkey_12"
        columns: ["assessoria_id", "class_id"]
        isOneToOne: false
        referencedRelation: "classes"
        referencedColumns: ["assessoria_id", "id"]
      },
    ]
  }
  attendances: {
    Row: {
      id: string | null
      assessoria_id: string
      class_id: string
      meeting_id: string
      membership_id: string
      student_id: string
      status: MvpEnums["attendance_status"]
      recorded_by_team_member_id: string | null
      recorded_at: string | null
      note: string | null
      created_at: string
      updated_at: string
    }
    Insert: {
      id?: string | null
      assessoria_id: string
      class_id: string
      meeting_id: string
      membership_id: string
      student_id: string
      status?: MvpEnums["attendance_status"]
      recorded_by_team_member_id?: string | null
      recorded_at?: string | null
      note?: string | null
      created_at?: string
      updated_at?: string
    }
    Update: {
      id?: string | null
      assessoria_id?: string
      class_id?: string
      meeting_id?: string
      membership_id?: string
      student_id?: string
      status?: MvpEnums["attendance_status"]
      recorded_by_team_member_id?: string | null
      recorded_at?: string | null
      note?: string | null
      created_at?: string
      updated_at?: string
    }
    Relationships: [
      {
        foreignKeyName: "attendances_assessoria_id_class_id_meeting_id_fkey_14"
        columns: ["assessoria_id", "class_id", "meeting_id"]
        isOneToOne: false
        referencedRelation: "class_meetings"
        referencedColumns: ["assessoria_id", "class_id", "id"]
      },
      {
        foreignKeyName: "attendances_assessoria_id_class_id_student_id_membership_id_fkey_15"
        columns: ["assessoria_id", "class_id", "student_id", "membership_id"]
        isOneToOne: false
        referencedRelation: "class_memberships"
        referencedColumns: ["assessoria_id", "class_id", "student_id", "id"]
      },
      {
        foreignKeyName: "attendances_assessoria_id_recorded_by_team_member_id_fkey_16"
        columns: ["assessoria_id", "recorded_by_team_member_id"]
        isOneToOne: false
        referencedRelation: "team_members"
        referencedColumns: ["assessoria_id", "id"]
      },
    ]
  }
  absence_justifications: {
    Row: {
      id: string | null
      assessoria_id: string
      attendance_id: string
      submitted_by_user_id: string
      reason: string
      submitted_at: string
      reviewed_by_team_member_id: string | null
      reviewed_at: string | null
      created_at: string
      updated_at: string
    }
    Insert: {
      id?: string | null
      assessoria_id: string
      attendance_id: string
      submitted_by_user_id: string
      reason: string
      submitted_at?: string
      reviewed_by_team_member_id?: string | null
      reviewed_at?: string | null
      created_at?: string
      updated_at?: string
    }
    Update: {
      id?: string | null
      assessoria_id?: string
      attendance_id?: string
      submitted_by_user_id?: string
      reason?: string
      submitted_at?: string
      reviewed_by_team_member_id?: string | null
      reviewed_at?: string | null
      created_at?: string
      updated_at?: string
    }
    Relationships: [
      {
        foreignKeyName: "absence_justifications_assessoria_id_attendance_id_fkey_12"
        columns: ["assessoria_id", "attendance_id"]
        isOneToOne: false
        referencedRelation: "attendances"
        referencedColumns: ["assessoria_id", "id"]
      },
      {
        foreignKeyName: "absence_justifications_assessoria_id_reviewed_by_team_member_id_fkey_14"
        columns: ["assessoria_id", "reviewed_by_team_member_id"]
        isOneToOne: false
        referencedRelation: "team_members"
        referencedColumns: ["assessoria_id", "id"]
      },
    ]
  }
  plans: {
    Row: {
      id: string | null
      assessoria_id: string
      name: string
      description: string | null
      active: boolean
      created_at: string
      updated_at: string
    }
    Insert: {
      id?: string | null
      assessoria_id: string
      name: string
      description?: string | null
      active?: boolean
      created_at?: string
      updated_at?: string
    }
    Update: {
      id?: string | null
      assessoria_id?: string
      name?: string
      description?: string | null
      active?: boolean
      created_at?: string
      updated_at?: string
    }
    Relationships: [
      {
        foreignKeyName: "plans_assessoria_id_fkey_9"
        columns: ["assessoria_id"]
        isOneToOne: false
        referencedRelation: "assessorias"
        referencedColumns: ["id"]
      },
    ]
  }
  plan_versions: {
    Row: {
      id: string | null
      assessoria_id: string
      plan_id: string
      version_number: number
      amount_cents: number
      currency: string
      periodicity: string
      due_day: number
      rules: MvpJson
      effective_from: string
      effective_until: string | null
      created_at: string
      updated_at: string
    }
    Insert: {
      id?: string | null
      assessoria_id: string
      plan_id: string
      version_number: number
      amount_cents: number
      currency?: string
      periodicity: string
      due_day: number
      rules?: MvpJson
      effective_from: string
      effective_until?: string | null
      created_at?: string
      updated_at?: string
    }
    Update: {
      id?: string | null
      assessoria_id?: string
      plan_id?: string
      version_number?: number
      amount_cents?: number
      currency?: string
      periodicity?: string
      due_day?: number
      rules?: MvpJson
      effective_from?: string
      effective_until?: string | null
      created_at?: string
      updated_at?: string
    }
    Relationships: [
      {
        foreignKeyName: "plan_versions_assessoria_id_plan_id_fkey_16"
        columns: ["assessoria_id", "plan_id"]
        isOneToOne: false
        referencedRelation: "plans"
        referencedColumns: ["assessoria_id", "id"]
      },
    ]
  }
  subscriptions: {
    Row: {
      id: string | null
      assessoria_id: string
      student_id: string
      enrollment_id: string
      plan_id: string
      plan_version_id: string
      status: MvpEnums["subscription_status"]
      amount_cents: number
      currency: string
      periodicity: string
      due_day: number
      starts_on: string
      ends_on: string | null
      created_at: string
      updated_at: string
    }
    Insert: {
      id?: string | null
      assessoria_id: string
      student_id: string
      enrollment_id: string
      plan_id: string
      plan_version_id: string
      status?: MvpEnums["subscription_status"]
      amount_cents: number
      currency?: string
      periodicity: string
      due_day: number
      starts_on: string
      ends_on?: string | null
      created_at?: string
      updated_at?: string
    }
    Update: {
      id?: string | null
      assessoria_id?: string
      student_id?: string
      enrollment_id?: string
      plan_id?: string
      plan_version_id?: string
      status?: MvpEnums["subscription_status"]
      amount_cents?: number
      currency?: string
      periodicity?: string
      due_day?: number
      starts_on?: string
      ends_on?: string | null
      created_at?: string
      updated_at?: string
    }
    Relationships: [
      {
        foreignKeyName: "subscriptions_assessoria_id_student_id_fkey_17"
        columns: ["assessoria_id", "student_id"]
        isOneToOne: false
        referencedRelation: "students"
        referencedColumns: ["assessoria_id", "id"]
      },
      {
        foreignKeyName: "subscriptions_assessoria_id_student_id_enrollment_id_fkey_18"
        columns: ["assessoria_id", "student_id", "enrollment_id"]
        isOneToOne: false
        referencedRelation: "enrollments"
        referencedColumns: ["assessoria_id", "student_id", "id"]
      },
      {
        foreignKeyName: "subscriptions_assessoria_id_plan_id_plan_version_id_fkey_19"
        columns: ["assessoria_id", "plan_id", "plan_version_id"]
        isOneToOne: false
        referencedRelation: "plan_versions"
        referencedColumns: ["assessoria_id", "plan_id", "id"]
      },
    ]
  }
  subscription_history: {
    Row: {
      id: string | null
      assessoria_id: string
      subscription_id: string
      previous_status: MvpEnums["subscription_status"] | null
      new_status: MvpEnums["subscription_status"]
      actor_team_member_id: string | null
      reason: string | null
      occurred_at: string
      created_at: string
    }
    Insert: {
      id?: string | null
      assessoria_id: string
      subscription_id: string
      previous_status?: MvpEnums["subscription_status"] | null
      new_status: MvpEnums["subscription_status"]
      actor_team_member_id?: string | null
      reason?: string | null
      occurred_at?: string
      created_at?: string
    }
    Update: {
      id?: string | null
      assessoria_id?: string
      subscription_id?: string
      previous_status?: MvpEnums["subscription_status"] | null
      new_status?: MvpEnums["subscription_status"]
      actor_team_member_id?: string | null
      reason?: string | null
      occurred_at?: string
      created_at?: string
    }
    Relationships: [
      {
        foreignKeyName: "subscription_history_assessoria_id_subscription_id_fkey_10"
        columns: ["assessoria_id", "subscription_id"]
        isOneToOne: false
        referencedRelation: "subscriptions"
        referencedColumns: ["assessoria_id", "id"]
      },
      {
        foreignKeyName: "subscription_history_assessoria_id_actor_team_member_id_fkey_11"
        columns: ["assessoria_id", "actor_team_member_id"]
        isOneToOne: false
        referencedRelation: "team_members"
        referencedColumns: ["assessoria_id", "id"]
      },
    ]
  }
  billing_cycles: {
    Row: {
      id: string | null
      assessoria_id: string
      subscription_id: string
      generation_run_id: string
      cycle_key: string
      period_starts_on: string
      period_ends_on: string
      due_on: string
      created_at: string
      updated_at: string
    }
    Insert: {
      id?: string | null
      assessoria_id: string
      subscription_id: string
      generation_run_id: string
      cycle_key: string
      period_starts_on: string
      period_ends_on: string
      due_on: string
      created_at?: string
      updated_at?: string
    }
    Update: {
      id?: string | null
      assessoria_id?: string
      subscription_id?: string
      generation_run_id?: string
      cycle_key?: string
      period_starts_on?: string
      period_ends_on?: string
      due_on?: string
      created_at?: string
      updated_at?: string
    }
    Relationships: [
      {
        foreignKeyName: "billing_cycles_assessoria_id_subscription_id_fkey_13"
        columns: ["assessoria_id", "subscription_id"]
        isOneToOne: false
        referencedRelation: "subscriptions"
        referencedColumns: ["assessoria_id", "id"]
      },
    ]
  }
  billing_generation_runs: {
    Row: {
      id: string | null
      assessoria_id: string
      window_starts_on: string
      window_ends_on: string
      status: string
      expected_count: number
      generated_count: number
      error_code: string | null
      started_at: string
      completed_at: string | null
      created_at: string
      updated_at: string
    }
    Insert: {
      id?: string | null
      assessoria_id: string
      window_starts_on: string
      window_ends_on: string
      status: string
      expected_count?: number
      generated_count?: number
      error_code?: string | null
      started_at?: string
      completed_at?: string | null
      created_at?: string
      updated_at?: string
    }
    Update: {
      id?: string | null
      assessoria_id?: string
      window_starts_on?: string
      window_ends_on?: string
      status?: string
      expected_count?: number
      generated_count?: number
      error_code?: string | null
      started_at?: string
      completed_at?: string | null
      created_at?: string
      updated_at?: string
    }
    Relationships: [
      {
        foreignKeyName: "billing_generation_runs_assessoria_id_fkey_13"
        columns: ["assessoria_id"]
        isOneToOne: false
        referencedRelation: "assessorias"
        referencedColumns: ["id"]
      },
    ]
  }
  billing_generation_watermarks: {
    Row: {
      id: string | null
      assessoria_id: string
      subscription_id: string
      last_cycle_key: string
      generation_run_id: string
      created_at: string
      updated_at: string
    }
    Insert: {
      id?: string | null
      assessoria_id: string
      subscription_id: string
      last_cycle_key: string
      generation_run_id: string
      created_at?: string
      updated_at?: string
    }
    Update: {
      id?: string | null
      assessoria_id?: string
      subscription_id?: string
      last_cycle_key?: string
      generation_run_id?: string
      created_at?: string
      updated_at?: string
    }
    Relationships: [
      {
        foreignKeyName: "billing_generation_watermarks_assessoria_id_subscription_id_fkey_9"
        columns: ["assessoria_id", "subscription_id"]
        isOneToOne: false
        referencedRelation: "subscriptions"
        referencedColumns: ["assessoria_id", "id"]
      },
      {
        foreignKeyName: "billing_generation_watermarks_assessoria_id_generation_run_id_fkey_10"
        columns: ["assessoria_id", "generation_run_id"]
        isOneToOne: false
        referencedRelation: "billing_generation_runs"
        referencedColumns: ["assessoria_id", "id"]
      },
    ]
  }
  charges: {
    Row: {
      id: string | null
      assessoria_id: string
      student_id: string
      subscription_id: string
      billing_cycle_id: string
      cycle_key: string
      status: MvpEnums["charge_status"]
      amount_cents: number
      currency: string
      due_on: string
      paid_at: string | null
      effective_fact_at: string | null
      legacy_cobranca_id: string | null
      created_at: string
      updated_at: string
    }
    Insert: {
      id?: string | null
      assessoria_id: string
      student_id: string
      subscription_id: string
      billing_cycle_id: string
      cycle_key: string
      status?: MvpEnums["charge_status"]
      amount_cents: number
      currency?: string
      due_on: string
      paid_at?: string | null
      effective_fact_at?: string | null
      legacy_cobranca_id?: string | null
      created_at?: string
      updated_at?: string
    }
    Update: {
      id?: string | null
      assessoria_id?: string
      student_id?: string
      subscription_id?: string
      billing_cycle_id?: string
      cycle_key?: string
      status?: MvpEnums["charge_status"]
      amount_cents?: number
      currency?: string
      due_on?: string
      paid_at?: string | null
      effective_fact_at?: string | null
      legacy_cobranca_id?: string | null
      created_at?: string
      updated_at?: string
    }
    Relationships: [
      {
        foreignKeyName: "charges_assessoria_id_student_id_subscription_id_fkey_19"
        columns: ["assessoria_id", "student_id", "subscription_id"]
        isOneToOne: false
        referencedRelation: "subscriptions"
        referencedColumns: ["assessoria_id", "student_id", "id"]
      },
      {
        foreignKeyName: "charges_assessoria_id_subscription_id_cycle_key_billing_cycle_id_fkey_20"
        columns: ["assessoria_id", "subscription_id", "cycle_key", "billing_cycle_id"]
        isOneToOne: false
        referencedRelation: "billing_cycles"
        referencedColumns: ["assessoria_id", "subscription_id", "cycle_key", "id"]
      },
      {
        foreignKeyName: "charges_assessoria_id_legacy_cobranca_id_fkey_21"
        columns: ["assessoria_id", "legacy_cobranca_id"]
        isOneToOne: false
        referencedRelation: "cobrancas"
        referencedColumns: ["assessoria_id", "id"]
      },
    ]
  }
  charge_adjustments: {
    Row: {
      id: string | null
      assessoria_id: string
      charge_id: string
      kind: string
      amount_cents: number
      reason: string
      actor_team_member_id: string
      created_at: string
    }
    Insert: {
      id?: string | null
      assessoria_id: string
      charge_id: string
      kind: string
      amount_cents: number
      reason: string
      actor_team_member_id: string
      created_at?: string
    }
    Update: {
      id?: string | null
      assessoria_id?: string
      charge_id?: string
      kind?: string
      amount_cents?: number
      reason?: string
      actor_team_member_id?: string
      created_at?: string
    }
    Relationships: [
      {
        foreignKeyName: "charge_adjustments_assessoria_id_charge_id_fkey_9"
        columns: ["assessoria_id", "charge_id"]
        isOneToOne: false
        referencedRelation: "charges"
        referencedColumns: ["assessoria_id", "id"]
      },
      {
        foreignKeyName: "charge_adjustments_assessoria_id_actor_team_member_id_fkey_10"
        columns: ["assessoria_id", "actor_team_member_id"]
        isOneToOne: false
        referencedRelation: "team_members"
        referencedColumns: ["assessoria_id", "id"]
      },
    ]
  }
  payment_checkouts: {
    Row: {
      id: string | null
      assessoria_id: string
      charge_id: string
      provider: string
      method: string
      status: MvpEnums["checkout_status"]
      idempotency_key: string
      provider_checkout_id: string | null
      checkout_url: string | null
      expires_at: string | null
      created_at: string
      updated_at: string
    }
    Insert: {
      id?: string | null
      assessoria_id: string
      charge_id: string
      provider: string
      method: string
      status?: MvpEnums["checkout_status"]
      idempotency_key: string
      provider_checkout_id?: string | null
      checkout_url?: string | null
      expires_at?: string | null
      created_at?: string
      updated_at?: string
    }
    Update: {
      id?: string | null
      assessoria_id?: string
      charge_id?: string
      provider?: string
      method?: string
      status?: MvpEnums["checkout_status"]
      idempotency_key?: string
      provider_checkout_id?: string | null
      checkout_url?: string | null
      expires_at?: string | null
      created_at?: string
      updated_at?: string
    }
    Relationships: [
      {
        foreignKeyName: "payment_checkouts_assessoria_id_charge_id_fkey_15"
        columns: ["assessoria_id", "charge_id"]
        isOneToOne: false
        referencedRelation: "charges"
        referencedColumns: ["assessoria_id", "id"]
      },
    ]
  }
  payments: {
    Row: {
      id: string | null
      assessoria_id: string
      charge_id: string
      provider: string
      external_payment_id: string | null
      idempotency_key: string | null
      status: MvpEnums["payment_status"]
      amount_cents: number
      currency: string
      authorized_at: string | null
      confirmed_at: string | null
      provider_occurred_at: string | null
      provider_sequence: number | null
      effective_fact_id: string | null
      created_at: string
      updated_at: string
    }
    Insert: {
      id?: string | null
      assessoria_id: string
      charge_id: string
      provider: string
      external_payment_id?: string | null
      idempotency_key?: string | null
      status?: MvpEnums["payment_status"]
      amount_cents: number
      currency?: string
      authorized_at?: string | null
      confirmed_at?: string | null
      provider_occurred_at?: string | null
      provider_sequence?: number | null
      effective_fact_id?: string | null
      created_at?: string
      updated_at?: string
    }
    Update: {
      id?: string | null
      assessoria_id?: string
      charge_id?: string
      provider?: string
      external_payment_id?: string | null
      idempotency_key?: string | null
      status?: MvpEnums["payment_status"]
      amount_cents?: number
      currency?: string
      authorized_at?: string | null
      confirmed_at?: string | null
      provider_occurred_at?: string | null
      provider_sequence?: number | null
      effective_fact_id?: string | null
      created_at?: string
      updated_at?: string
    }
    Relationships: [
      {
        foreignKeyName: "payments_assessoria_id_charge_id_fkey_19"
        columns: ["assessoria_id", "charge_id"]
        isOneToOne: false
        referencedRelation: "charges"
        referencedColumns: ["assessoria_id", "id"]
      },
    ]
  }
  payment_settlements: {
    Row: {
      id: string | null
      assessoria_id: string
      payment_id: string
      status: MvpEnums["settlement_status"]
      gross_amount_cents: number
      fee_amount_cents: number
      net_amount_cents: number
      currency: string
      external_settlement_id: string | null
      received_at: string | null
      available_at: string | null
      effective_fact_id: string | null
      created_at: string
      updated_at: string
    }
    Insert: {
      id?: string | null
      assessoria_id: string
      payment_id: string
      status?: MvpEnums["settlement_status"]
      gross_amount_cents: number
      fee_amount_cents?: number
      net_amount_cents: number
      currency?: string
      external_settlement_id?: string | null
      received_at?: string | null
      available_at?: string | null
      effective_fact_id?: string | null
      created_at?: string
      updated_at?: string
    }
    Update: {
      id?: string | null
      assessoria_id?: string
      payment_id?: string
      status?: MvpEnums["settlement_status"]
      gross_amount_cents?: number
      fee_amount_cents?: number
      net_amount_cents?: number
      currency?: string
      external_settlement_id?: string | null
      received_at?: string | null
      available_at?: string | null
      effective_fact_id?: string | null
      created_at?: string
      updated_at?: string
    }
    Relationships: [
      {
        foreignKeyName: "payment_settlements_assessoria_id_payment_id_fkey_17"
        columns: ["assessoria_id", "payment_id"]
        isOneToOne: false
        referencedRelation: "payments"
        referencedColumns: ["assessoria_id", "id"]
      },
    ]
  }
  payment_refunds: {
    Row: {
      id: string | null
      assessoria_id: string
      payment_id: string
      provider: string
      external_refund_id: string
      status: MvpEnums["refund_status"]
      amount_cents: number
      reason: string | null
      provider_occurred_at: string | null
      created_at: string
      updated_at: string
    }
    Insert: {
      id?: string | null
      assessoria_id: string
      payment_id: string
      provider: string
      external_refund_id: string
      status?: MvpEnums["refund_status"]
      amount_cents: number
      reason?: string | null
      provider_occurred_at?: string | null
      created_at?: string
      updated_at?: string
    }
    Update: {
      id?: string | null
      assessoria_id?: string
      payment_id?: string
      provider?: string
      external_refund_id?: string
      status?: MvpEnums["refund_status"]
      amount_cents?: number
      reason?: string | null
      provider_occurred_at?: string | null
      created_at?: string
      updated_at?: string
    }
    Relationships: [
      {
        foreignKeyName: "payment_refunds_assessoria_id_payment_id_fkey_13"
        columns: ["assessoria_id", "payment_id"]
        isOneToOne: false
        referencedRelation: "payments"
        referencedColumns: ["assessoria_id", "id"]
      },
    ]
  }
  payment_disputes: {
    Row: {
      id: string | null
      assessoria_id: string
      payment_id: string
      provider: string
      external_dispute_id: string
      status: MvpEnums["dispute_status"]
      amount_cents: number | null
      reason: string | null
      provider_occurred_at: string | null
      created_at: string
      updated_at: string
    }
    Insert: {
      id?: string | null
      assessoria_id: string
      payment_id: string
      provider: string
      external_dispute_id: string
      status?: MvpEnums["dispute_status"]
      amount_cents?: number | null
      reason?: string | null
      provider_occurred_at?: string | null
      created_at?: string
      updated_at?: string
    }
    Update: {
      id?: string | null
      assessoria_id?: string
      payment_id?: string
      provider?: string
      external_dispute_id?: string
      status?: MvpEnums["dispute_status"]
      amount_cents?: number | null
      reason?: string | null
      provider_occurred_at?: string | null
      created_at?: string
      updated_at?: string
    }
    Relationships: [
      {
        foreignKeyName: "payment_disputes_assessoria_id_payment_id_fkey_13"
        columns: ["assessoria_id", "payment_id"]
        isOneToOne: false
        referencedRelation: "payments"
        referencedColumns: ["assessoria_id", "id"]
      },
    ]
  }
  financial_categories: {
    Row: {
      id: string | null
      assessoria_id: string
      kind: string
      name: string
      active: boolean
      created_at: string
      updated_at: string
    }
    Insert: {
      id?: string | null
      assessoria_id: string
      kind: string
      name: string
      active?: boolean
      created_at?: string
      updated_at?: string
    }
    Update: {
      id?: string | null
      assessoria_id?: string
      kind?: string
      name?: string
      active?: boolean
      created_at?: string
      updated_at?: string
    }
    Relationships: [
      {
        foreignKeyName: "financial_categories_assessoria_id_fkey_9"
        columns: ["assessoria_id"]
        isOneToOne: false
        referencedRelation: "assessorias"
        referencedColumns: ["id"]
      },
    ]
  }
  expenses: {
    Row: {
      id: string | null
      assessoria_id: string
      category_id: string
      description: string
      status: MvpEnums["expense_status"]
      amount_cents: number
      currency: string
      due_on: string | null
      paid_at: string | null
      created_by_team_member_id: string
      created_at: string
      updated_at: string
    }
    Insert: {
      id?: string | null
      assessoria_id: string
      category_id: string
      description: string
      status?: MvpEnums["expense_status"]
      amount_cents: number
      currency?: string
      due_on?: string | null
      paid_at?: string | null
      created_by_team_member_id: string
      created_at?: string
      updated_at?: string
    }
    Update: {
      id?: string | null
      assessoria_id?: string
      category_id?: string
      description?: string
      status?: MvpEnums["expense_status"]
      amount_cents?: number
      currency?: string
      due_on?: string | null
      paid_at?: string | null
      created_by_team_member_id?: string
      created_at?: string
      updated_at?: string
    }
    Relationships: [
      {
        foreignKeyName: "expenses_assessoria_id_category_id_fkey_13"
        columns: ["assessoria_id", "category_id"]
        isOneToOne: false
        referencedRelation: "financial_categories"
        referencedColumns: ["assessoria_id", "id"]
      },
      {
        foreignKeyName: "expenses_assessoria_id_created_by_team_member_id_fkey_14"
        columns: ["assessoria_id", "created_by_team_member_id"]
        isOneToOne: false
        referencedRelation: "team_members"
        referencedColumns: ["assessoria_id", "id"]
      },
    ]
  }
  other_revenues: {
    Row: {
      id: string | null
      assessoria_id: string
      category_id: string
      description: string
      status: string
      amount_cents: number
      currency: string
      expected_on: string | null
      received_at: string | null
      created_by_team_member_id: string
      created_at: string
      updated_at: string
    }
    Insert: {
      id?: string | null
      assessoria_id: string
      category_id: string
      description: string
      status?: string
      amount_cents: number
      currency?: string
      expected_on?: string | null
      received_at?: string | null
      created_by_team_member_id: string
      created_at?: string
      updated_at?: string
    }
    Update: {
      id?: string | null
      assessoria_id?: string
      category_id?: string
      description?: string
      status?: string
      amount_cents?: number
      currency?: string
      expected_on?: string | null
      received_at?: string | null
      created_by_team_member_id?: string
      created_at?: string
      updated_at?: string
    }
    Relationships: [
      {
        foreignKeyName: "other_revenues_assessoria_id_category_id_fkey_13"
        columns: ["assessoria_id", "category_id"]
        isOneToOne: false
        referencedRelation: "financial_categories"
        referencedColumns: ["assessoria_id", "id"]
      },
      {
        foreignKeyName: "other_revenues_assessoria_id_created_by_team_member_id_fkey_14"
        columns: ["assessoria_id", "created_by_team_member_id"]
        isOneToOne: false
        referencedRelation: "team_members"
        referencedColumns: ["assessoria_id", "id"]
      },
    ]
  }
  cash_movements: {
    Row: {
      id: string | null
      assessoria_id: string
      direction: string
      source_type: string
      source_id: string
      settlement_id: string | null
      expense_id: string | null
      other_revenue_id: string | null
      idempotency_key: string
      amount_cents: number
      currency: string
      occurred_at: string
      created_at: string
    }
    Insert: {
      id?: string | null
      assessoria_id: string
      direction: string
      source_type: string
      source_id: string
      settlement_id?: string | null
      expense_id?: string | null
      other_revenue_id?: string | null
      idempotency_key: string
      amount_cents: number
      currency?: string
      occurred_at: string
      created_at?: string
    }
    Update: {
      id?: string | null
      assessoria_id?: string
      direction?: string
      source_type?: string
      source_id?: string
      settlement_id?: string | null
      expense_id?: string | null
      other_revenue_id?: string | null
      idempotency_key?: string
      amount_cents?: number
      currency?: string
      occurred_at?: string
      created_at?: string
    }
    Relationships: [
      {
        foreignKeyName: "cash_movements_assessoria_id_fkey_16"
        columns: ["assessoria_id"]
        isOneToOne: false
        referencedRelation: "assessorias"
        referencedColumns: ["id"]
      },
      {
        foreignKeyName: "cash_movements_assessoria_id_settlement_id_fkey_17"
        columns: ["assessoria_id", "settlement_id"]
        isOneToOne: false
        referencedRelation: "payment_settlements"
        referencedColumns: ["assessoria_id", "id"]
      },
      {
        foreignKeyName: "cash_movements_assessoria_id_expense_id_fkey_18"
        columns: ["assessoria_id", "expense_id"]
        isOneToOne: false
        referencedRelation: "expenses"
        referencedColumns: ["assessoria_id", "id"]
      },
      {
        foreignKeyName: "cash_movements_assessoria_id_other_revenue_id_fkey_19"
        columns: ["assessoria_id", "other_revenue_id"]
        isOneToOne: false
        referencedRelation: "other_revenues"
        referencedColumns: ["assessoria_id", "id"]
      },
    ]
  }
  provider_events: {
    Row: {
      id: string | null
      assessoria_id: string
      provider: string
      external_event_id: string
      event_type: string
      status: MvpEnums["provider_event_status"]
      resource_type: string | null
      resource_external_id: string | null
      sanitized_payload: MvpJson
      provider_occurred_at: string | null
      provider_sequence: number | null
      received_at: string
      processing_started_at: string | null
      lease_expires_at: string | null
      next_attempt_at: string
      attempt_count: number
      last_error_code: string | null
      processed_at: string | null
      created_at: string
      updated_at: string
    }
    Insert: {
      id?: string | null
      assessoria_id: string
      provider: string
      external_event_id: string
      event_type: string
      status?: MvpEnums["provider_event_status"]
      resource_type?: string | null
      resource_external_id?: string | null
      sanitized_payload?: MvpJson
      provider_occurred_at?: string | null
      provider_sequence?: number | null
      received_at?: string
      processing_started_at?: string | null
      lease_expires_at?: string | null
      next_attempt_at?: string
      attempt_count?: number
      last_error_code?: string | null
      processed_at?: string | null
      created_at?: string
      updated_at?: string
    }
    Update: {
      id?: string | null
      assessoria_id?: string
      provider?: string
      external_event_id?: string
      event_type?: string
      status?: MvpEnums["provider_event_status"]
      resource_type?: string | null
      resource_external_id?: string | null
      sanitized_payload?: MvpJson
      provider_occurred_at?: string | null
      provider_sequence?: number | null
      received_at?: string
      processing_started_at?: string | null
      lease_expires_at?: string | null
      next_attempt_at?: string
      attempt_count?: number
      last_error_code?: string | null
      processed_at?: string | null
      created_at?: string
      updated_at?: string
    }
    Relationships: [
      {
        foreignKeyName: "provider_events_assessoria_id_fkey_22"
        columns: ["assessoria_id"]
        isOneToOne: false
        referencedRelation: "assessorias"
        referencedColumns: ["id"]
      },
    ]
  }
  integration_attempts: {
    Row: {
      id: string | null
      assessoria_id: string
      provider: string
      operation: string
      correlation_id: string
      resource_type: string | null
      resource_id: string | null
      status: string
      attempt_number: number
      response_code: string | null
      error_code: string | null
      started_at: string
      completed_at: string | null
      created_at: string
      updated_at: string
    }
    Insert: {
      id?: string | null
      assessoria_id: string
      provider: string
      operation: string
      correlation_id: string
      resource_type?: string | null
      resource_id?: string | null
      status: string
      attempt_number?: number
      response_code?: string | null
      error_code?: string | null
      started_at?: string
      completed_at?: string | null
      created_at?: string
      updated_at?: string
    }
    Update: {
      id?: string | null
      assessoria_id?: string
      provider?: string
      operation?: string
      correlation_id?: string
      resource_type?: string | null
      resource_id?: string | null
      status?: string
      attempt_number?: number
      response_code?: string | null
      error_code?: string | null
      started_at?: string
      completed_at?: string | null
      created_at?: string
      updated_at?: string
    }
    Relationships: [
      {
        foreignKeyName: "integration_attempts_assessoria_id_fkey_17"
        columns: ["assessoria_id"]
        isOneToOne: false
        referencedRelation: "assessorias"
        referencedColumns: ["id"]
      },
    ]
  }
  contact_preferences: {
    Row: {
      id: string | null
      assessoria_id: string
      student_id: string
      whatsapp_phone: string | null
      whatsapp_opt_in: boolean
      whatsapp_opt_in_at: string | null
      whatsapp_opt_out_at: string | null
      billing_messages_enabled: boolean
      created_at: string
      updated_at: string
    }
    Insert: {
      id?: string | null
      assessoria_id: string
      student_id: string
      whatsapp_phone?: string | null
      whatsapp_opt_in?: boolean
      whatsapp_opt_in_at?: string | null
      whatsapp_opt_out_at?: string | null
      billing_messages_enabled?: boolean
      created_at?: string
      updated_at?: string
    }
    Update: {
      id?: string | null
      assessoria_id?: string
      student_id?: string
      whatsapp_phone?: string | null
      whatsapp_opt_in?: boolean
      whatsapp_opt_in_at?: string | null
      whatsapp_opt_out_at?: string | null
      billing_messages_enabled?: boolean
      created_at?: string
      updated_at?: string
    }
    Relationships: [
      {
        foreignKeyName: "contact_preferences_assessoria_id_student_id_fkey_12"
        columns: ["assessoria_id", "student_id"]
        isOneToOne: false
        referencedRelation: "students"
        referencedColumns: ["assessoria_id", "id"]
      },
    ]
  }
  message_templates: {
    Row: {
      id: string | null
      assessoria_id: string
      code: string
      version: number
      provider: string
      provider_template_name: string | null
      locale: string
      body_preview: string
      active: boolean
      created_at: string
      updated_at: string
    }
    Insert: {
      id?: string | null
      assessoria_id: string
      code: string
      version: number
      provider?: string
      provider_template_name?: string | null
      locale?: string
      body_preview: string
      active?: boolean
      created_at?: string
      updated_at?: string
    }
    Update: {
      id?: string | null
      assessoria_id?: string
      code?: string
      version?: number
      provider?: string
      provider_template_name?: string | null
      locale?: string
      body_preview?: string
      active?: boolean
      created_at?: string
      updated_at?: string
    }
    Relationships: [
      {
        foreignKeyName: "message_templates_assessoria_id_fkey_14"
        columns: ["assessoria_id"]
        isOneToOne: false
        referencedRelation: "assessorias"
        referencedColumns: ["id"]
      },
    ]
  }
  message_jobs: {
    Row: {
      id: string | null
      assessoria_id: string
      charge_id: string
      student_id: string
      template_id: string
      template_version: number
      cadence_offset: number
      status: MvpEnums["message_status"]
      scheduled_for: string
      claimed_at: string | null
      lease_expires_at: string | null
      next_attempt_at: string
      attempt_count: number
      provider_message_id: string | null
      last_error_code: string | null
      submitted_at: string | null
      created_at: string
      updated_at: string
    }
    Insert: {
      id?: string | null
      assessoria_id: string
      charge_id: string
      student_id: string
      template_id: string
      template_version: number
      cadence_offset: number
      status?: MvpEnums["message_status"]
      scheduled_for: string
      claimed_at?: string | null
      lease_expires_at?: string | null
      next_attempt_at?: string
      attempt_count?: number
      provider_message_id?: string | null
      last_error_code?: string | null
      submitted_at?: string | null
      created_at?: string
      updated_at?: string
    }
    Update: {
      id?: string | null
      assessoria_id?: string
      charge_id?: string
      student_id?: string
      template_id?: string
      template_version?: number
      cadence_offset?: number
      status?: MvpEnums["message_status"]
      scheduled_for?: string
      claimed_at?: string | null
      lease_expires_at?: string | null
      next_attempt_at?: string
      attempt_count?: number
      provider_message_id?: string | null
      last_error_code?: string | null
      submitted_at?: string | null
      created_at?: string
      updated_at?: string
    }
    Relationships: [
      {
        foreignKeyName: "message_jobs_assessoria_id_student_id_charge_id_fkey_20"
        columns: ["assessoria_id", "student_id", "charge_id"]
        isOneToOne: false
        referencedRelation: "charges"
        referencedColumns: ["assessoria_id", "student_id", "id"]
      },
      {
        foreignKeyName: "message_jobs_assessoria_id_template_id_template_version_fkey_21"
        columns: ["assessoria_id", "template_id", "template_version"]
        isOneToOne: false
        referencedRelation: "message_templates"
        referencedColumns: ["assessoria_id", "id", "version"]
      },
    ]
  }
  message_events: {
    Row: {
      id: string | null
      assessoria_id: string
      message_job_id: string | null
      provider: string
      external_event_id: string
      provider_message_id: string
      delivery_status: MvpEnums["message_status"]
      processing_status: MvpEnums["provider_event_status"]
      provider_occurred_at: string
      received_at: string
      processing_started_at: string | null
      lease_expires_at: string | null
      next_attempt_at: string
      attempt_count: number
      processed_at: string | null
      last_error_code: string | null
      sanitized_payload: MvpJson
      created_at: string
    }
    Insert: {
      id?: string | null
      assessoria_id: string
      message_job_id?: string | null
      provider?: string
      external_event_id: string
      provider_message_id: string
      delivery_status: MvpEnums["message_status"]
      processing_status?: MvpEnums["provider_event_status"]
      provider_occurred_at: string
      received_at?: string
      processing_started_at?: string | null
      lease_expires_at?: string | null
      next_attempt_at?: string
      attempt_count?: number
      processed_at?: string | null
      last_error_code?: string | null
      sanitized_payload?: MvpJson
      created_at?: string
    }
    Update: {
      id?: string | null
      assessoria_id?: string
      message_job_id?: string | null
      provider?: string
      external_event_id?: string
      provider_message_id?: string
      delivery_status?: MvpEnums["message_status"]
      processing_status?: MvpEnums["provider_event_status"]
      provider_occurred_at?: string
      received_at?: string
      processing_started_at?: string | null
      lease_expires_at?: string | null
      next_attempt_at?: string
      attempt_count?: number
      processed_at?: string | null
      last_error_code?: string | null
      sanitized_payload?: MvpJson
      created_at?: string
    }
    Relationships: [
      {
        foreignKeyName: "message_events_assessoria_id_message_job_id_fkey_20"
        columns: ["assessoria_id", "message_job_id"]
        isOneToOne: false
        referencedRelation: "message_jobs"
        referencedColumns: ["assessoria_id", "id"]
      },
    ]
  }
  leads: {
    Row: {
      id: string | null
      assessoria_id: string
      name: string
      email: string | null
      phone: string | null
      deduplication_key: string
      status: MvpEnums["lead_status"]
      source: string | null
      converted_student_id: string | null
      consent_at: string | null
      closed_reason: string | null
      created_at: string
      updated_at: string
    }
    Insert: {
      id?: string | null
      assessoria_id: string
      name: string
      email?: string | null
      phone?: string | null
      deduplication_key: string
      status?: MvpEnums["lead_status"]
      source?: string | null
      converted_student_id?: string | null
      consent_at?: string | null
      closed_reason?: string | null
      created_at?: string
      updated_at?: string
    }
    Update: {
      id?: string | null
      assessoria_id?: string
      name?: string
      email?: string | null
      phone?: string | null
      deduplication_key?: string
      status?: MvpEnums["lead_status"]
      source?: string | null
      converted_student_id?: string | null
      consent_at?: string | null
      closed_reason?: string | null
      created_at?: string
      updated_at?: string
    }
    Relationships: [
      {
        foreignKeyName: "leads_assessoria_id_fkey_15"
        columns: ["assessoria_id"]
        isOneToOne: false
        referencedRelation: "assessorias"
        referencedColumns: ["id"]
      },
      {
        foreignKeyName: "leads_assessoria_id_converted_student_id_fkey_16"
        columns: ["assessoria_id", "converted_student_id"]
        isOneToOne: false
        referencedRelation: "students"
        referencedColumns: ["assessoria_id", "id"]
      },
    ]
  }
  lead_history: {
    Row: {
      id: string | null
      assessoria_id: string
      lead_id: string
      previous_status: MvpEnums["lead_status"] | null
      new_status: MvpEnums["lead_status"]
      actor_team_member_id: string | null
      note: string | null
      occurred_at: string
      created_at: string
    }
    Insert: {
      id?: string | null
      assessoria_id: string
      lead_id: string
      previous_status?: MvpEnums["lead_status"] | null
      new_status: MvpEnums["lead_status"]
      actor_team_member_id?: string | null
      note?: string | null
      occurred_at?: string
      created_at?: string
    }
    Update: {
      id?: string | null
      assessoria_id?: string
      lead_id?: string
      previous_status?: MvpEnums["lead_status"] | null
      new_status?: MvpEnums["lead_status"]
      actor_team_member_id?: string | null
      note?: string | null
      occurred_at?: string
      created_at?: string
    }
    Relationships: [
      {
        foreignKeyName: "lead_history_assessoria_id_lead_id_fkey_10"
        columns: ["assessoria_id", "lead_id"]
        isOneToOne: false
        referencedRelation: "leads"
        referencedColumns: ["assessoria_id", "id"]
      },
      {
        foreignKeyName: "lead_history_assessoria_id_actor_team_member_id_fkey_11"
        columns: ["assessoria_id", "actor_team_member_id"]
        isOneToOne: false
        referencedRelation: "team_members"
        referencedColumns: ["assessoria_id", "id"]
      },
    ]
  }
  audit_entries: {
    Row: {
      id: string | null
      assessoria_id: string
      actor_user_id: string | null
      actor_role: string
      action: string
      target_type: string
      target_id: string | null
      before_data: MvpJson | null
      after_data: MvpJson | null
      reason: string | null
      correlation_id: string
      occurred_at: string
      created_at: string
    }
    Insert: {
      id?: string | null
      assessoria_id: string
      actor_user_id?: string | null
      actor_role: string
      action: string
      target_type: string
      target_id?: string | null
      before_data?: MvpJson | null
      after_data?: MvpJson | null
      reason?: string | null
      correlation_id: string
      occurred_at?: string
      created_at?: string
    }
    Update: {
      id?: string | null
      assessoria_id?: string
      actor_user_id?: string | null
      actor_role?: string
      action?: string
      target_type?: string
      target_id?: string | null
      before_data?: MvpJson | null
      after_data?: MvpJson | null
      reason?: string | null
      correlation_id?: string
      occurred_at?: string
      created_at?: string
    }
    Relationships: [
      {
        foreignKeyName: "audit_entries_assessoria_id_fkey_14"
        columns: ["assessoria_id"]
        isOneToOne: false
        referencedRelation: "assessorias"
        referencedColumns: ["id"]
      },
    ]
  }
}
