"use client";
import { useActionState, useState } from "react";
import { recordAttendanceAction, type AttendanceActionState } from "@/app/(dashboard)/treinador/calendario/attendance-actions";
import type { AttendanceStatus } from "@/types/mvp-foundation";
const initial: AttendanceActionState = {};
const options: Array<{ value: AttendanceStatus; label: string }> = [{ value: "present", label: "Presente" }, { value: "absent", label: "Falta" }, { value: "excused", label: "Justificada" }, { value: "not_recorded", label: "Não registrada" }];
export function AttendanceBatchForm({ meetingId, disabled, students }: { meetingId: string; disabled: boolean; students: ReadonlyArray<{ id: string; name: string; status: AttendanceStatus }> }) {
  const [state, action, pending] = useActionState(recordAttendanceAction, initial);
  const [entries, setEntries] = useState(students.map((student) => ({ studentId: student.id, status: student.status === "not_recorded" ? "present" as AttendanceStatus : student.status })));
  return <form action={action} className="attendance-form"><input type="hidden" name="meetingId" value={meetingId} /><input type="hidden" name="entries" value={JSON.stringify(entries)} /><div className="attendance-form-heading"><div><h3>Chamada do encontro</h3><p className="field-hint">Marque cada aluno. Encontro cancelado ou não registrado não entra no indicador de faltas.</p></div><span>{students.length} alunos</span></div>{disabled ? <p className="form-error" role="alert">Este encontro foi cancelado e não aceita chamada.</p> : null}<ul className="attendance-list">{students.map((student, index) => <li key={student.id}><span>{student.name}</span><label><span className="sr-only">Situação de {student.name}</span><select className="input" disabled={disabled || pending} value={entries[index]?.status ?? "present"} onChange={(event) => setEntries((current) => current.map((entry, entryIndex) => entryIndex === index ? { ...entry, status: event.target.value as AttendanceStatus } : entry))}>{options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label></li>)}</ul>{state.error ? <p className="form-error" role="alert">{state.error}</p> : null}{state.success ? <p className="field-hint" role="status">Chamada registrada.</p> : null}<button className="button button-primary" type="submit" disabled={disabled || pending || !students.length}>{pending ? "Salvando…" : "Salvar chamada"}</button></form>;
}
