"use client";
import { useActionState } from "react";
import { createSubscriptionAction, markChargePaidAction } from "@/lib/actions/financial.actions";
import { queueBillingReminderAction, saveCommunicationPreferenceAction } from "@/lib/actions/communication.actions";
import { initialTrainingActionState } from "@/lib/actions/training.state";
import type { TrainerAthleteSummary } from "@/lib/services/athlete.service";
import { Button } from "@/components/ui/button";
export function SubscriptionForm({ athletes }: { athletes: TrainerAthleteSummary[] }) { const [state, action, pending] = useActionState(createSubscriptionAction, initialTrainingActionState); return <form action={action} className="training-form"><div className="training-form-grid"><div className="form-field"><label htmlFor="athleteId">Atleta</label><select className="input" id="athleteId" name="athleteId">{athletes.map((athlete) => <option key={athlete.id} value={athlete.id}>{athlete.nome}</option>)}</select></div><div className="form-field"><label htmlFor="amountCents">Valor (centavos)</label><input className="input" id="amountCents" min="0" name="amountCents" type="number" required /></div><div className="form-field"><label htmlFor="dueDay">Dia de vencimento</label><input className="input" id="dueDay" max="31" min="1" name="dueDay" type="number" required /></div></div><div className="training-form-grid"><div className="form-field"><label htmlFor="periodicity">Periodicidade</label><select className="input" id="periodicity" name="periodicity"><option value="mensal">Mensal</option><option value="trimestral">Trimestral</option><option value="semestral">Semestral</option><option value="anual">Anual</option></select></div><div className="form-field"><label htmlFor="paymentMethod">Método previsto</label><input className="input" id="paymentMethod" name="paymentMethod" /></div><div className="form-field"><label htmlFor="startDate">Início</label><input className="input" id="startDate" name="startDate" type="date" required /></div><div className="form-field"><label htmlFor="status">Situação</label><select className="input" id="status" name="status"><option value="ativa">Ativa</option><option value="suspensa">Suspensa</option><option value="isenta">Isenta</option></select></div></div>{state.error ? <p className="form-error">{state.error}</p> : null}{state.success ? <p className="form-success">{state.success}</p> : null}<Button disabled={pending} type="submit">{pending ? "Criando..." : "Criar assinatura"}</Button></form>; }
export function ChargePaidForm({ chargeId }: { chargeId: string }) { const [state, action, pending] = useActionState(markChargePaidAction, initialTrainingActionState); return <form action={action}><input name="chargeId" type="hidden" value={chargeId} />{state.error ? <p className="form-error">{state.error}</p> : null}<Button disabled={pending} type="submit" variant="secondary">{pending ? "Registrando..." : "Marcar como paga"}</Button></form>; }
export function CommunicationPreferenceForm({ athletes }: { athletes: TrainerAthleteSummary[] }) { const [state, action, pending] = useActionState(saveCommunicationPreferenceAction, initialTrainingActionState); return <form action={action} className="training-form"><div className="training-form-grid"><div className="form-field"><label htmlFor="consent-athlete">Atleta</label><select className="input" id="consent-athlete" name="athleteId">{athletes.map((athlete) => <option key={athlete.id} value={athlete.id}>{athlete.nome}</option>)}</select></div><div className="form-field"><label htmlFor="phone">WhatsApp</label><input className="input" id="phone" name="phone" /></div><div className="form-field"><label htmlFor="whatsappOptIn">Consentimento</label><select className="input" id="whatsappOptIn" name="whatsappOptIn"><option value="false">Sem opt-in</option><option value="true">Opt-in confirmado</option></select></div><div className="form-field"><label htmlFor="billingWhatsapp">Cobrança por WhatsApp</label><select className="input" id="billingWhatsapp" name="billingWhatsapp"><option value="false">Não autorizada</option><option value="true">Autorizada</option></select></div></div>{state.error ? <p className="form-error">{state.error}</p> : null}{state.success ? <p className="form-success">{state.success}</p> : null}<Button disabled={pending} type="submit">Salvar consentimento</Button></form>; }
export function QueueReminderForm({ chargeId }: { chargeId: string }) { const [state, action, pending] = useActionState(queueBillingReminderAction, initialTrainingActionState); return <form action={action} className="training-assignment-form"><input name="chargeId" type="hidden" value={chargeId} /><select className="input" name="templateCode"><option value="cobranca_proximo_vencimento">Próximo vencimento</option><option value="cobranca_vencida">Cobrança vencida</option></select>{state.error ? <p className="form-error">{state.error}</p> : null}{state.success ? <p className="form-success">{state.success}</p> : null}<Button disabled={pending} type="submit" variant="secondary">{pending ? "Preparando..." : "Preparar lembrete"}</Button></form>; }
