"use client";

import { useActionState } from "react";
import { completeTrainingAction, startTrainingAction } from "@/lib/actions/training-execution.actions";
import { initialTrainingActionState } from "@/lib/actions/training.state";
import { Button } from "@/components/ui/button";

export function TrainingExecutionForm({ assignmentId, status }: { assignmentId: string; status: "atribuido" | "em_andamento" | "concluido" | "cancelado" }) {
  const [startState, startAction, starting] = useActionState(startTrainingAction, initialTrainingActionState);
  const [completeState, completeAction, completing] = useActionState(completeTrainingAction, initialTrainingActionState);
  if (status === "concluido" || status === "cancelado") return null;
  if (status === "atribuido") return <form action={startAction}><input name="assignmentId" type="hidden" value={assignmentId} />{startState.error ? <p className="form-error">{startState.error}</p> : null}<Button disabled={starting} type="submit">{starting ? "Iniciando..." : "Iniciar treino"}</Button></form>;
  return <details className="training-assignment"><summary>Concluir treino</summary><form action={completeAction} className="training-form"><input name="assignmentId" type="hidden" value={assignmentId} /><div className="training-form-grid"><div className="form-field"><label htmlFor={`rpe-${assignmentId}`}>RPE (1 a 10)</label><input className="input" id={`rpe-${assignmentId}`} max="10" min="1" name="rpe" type="number" /></div><div className="form-field"><label htmlFor={`duration-${assignmentId}`}>Duração (min)</label><input className="input" id={`duration-${assignmentId}`} min="1" name="durationMinutes" type="number" /></div><div className="form-field"><label htmlFor={`distance-${assignmentId}`}>Distância (m)</label><input className="input" id={`distance-${assignmentId}`} min="1" name="distanceMeters" type="number" /></div></div><div className="training-form-grid"><div className="form-field"><label htmlFor={`region-${assignmentId}`}>Desconforto (opcional)</label><select className="input" id={`region-${assignmentId}`} name="discomfortRegion"><option value="">Sem desconforto</option><option value="pe">Pé</option><option value="tornozelo">Tornozelo</option><option value="panturrilha">Panturrilha</option><option value="joelho">Joelho</option><option value="coxa">Coxa</option><option value="quadril">Quadril</option><option value="lombar">Lombar</option><option value="outro">Outro</option></select></div><div className="form-field"><label htmlFor={`intensity-${assignmentId}`}>Intensidade (1 a 10)</label><input className="input" id={`intensity-${assignmentId}`} max="10" min="1" name="discomfortIntensity" type="number" /></div></div><div className="form-field"><label htmlFor={`note-${assignmentId}`}>Observação</label><textarea className="input" id={`note-${assignmentId}`} maxLength={500} name="note" rows={2} /></div>{completeState.error ? <p className="form-error">{completeState.error}</p> : null}<Button disabled={completing} type="submit">{completing ? "Registrando..." : "Registrar conclusão"}</Button></form></details>;
}
