create table public.preferencias_comunicacao (id uuid primary key default gen_random_uuid(), assessoria_id uuid not null, atleta_id uuid not null, whatsapp_telefone text, whatsapp_opt_in boolean not null default false, whatsapp_opt_in_em timestamptz, whatsapp_opt_out_em timestamptz, cobranca_whatsapp boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), constraint preferencias_comunicacao_atleta_fkey foreign key (assessoria_id, atleta_id) references public.atletas (assessoria_id, id), constraint preferencias_comunicacao_assessoria_atleta_key unique (assessoria_id, atleta_id), constraint preferencias_comunicacao_optin_check check ((whatsapp_opt_in = false and cobranca_whatsapp = false) or whatsapp_opt_in = true));
create table public.lembretes_cobranca (id uuid primary key default gen_random_uuid(), assessoria_id uuid not null, cobranca_id uuid not null, atleta_id uuid not null, canal text not null check (canal = 'whatsapp'), status text not null check (status in ('pendente','bloqueado','enviado','falhou','cancelado')), programado_para timestamptz not null, template_codigo text not null check (template_codigo in ('cobranca_proximo_vencimento','cobranca_vencida')), tentativas integer not null default 0 check (tentativas >= 0), ultimo_erro text, provider_message_id text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), constraint lembretes_cobranca_cobranca_fkey foreign key (assessoria_id, cobranca_id) references public.cobrancas (assessoria_id, id), constraint lembretes_cobranca_atleta_fkey foreign key (assessoria_id, atleta_id) references public.atletas (assessoria_id, id));
create index lembretes_cobranca_assessoria_atleta_created_idx on public.lembretes_cobranca (assessoria_id, atleta_id, created_at desc);
alter table public.preferencias_comunicacao enable row level security; alter table public.preferencias_comunicacao force row level security; alter table public.lembretes_cobranca enable row level security; alter table public.lembretes_cobranca force row level security;
create policy preferencias_comunicacao_trainer on public.preferencias_comunicacao for all to authenticated using (private.is_treinador(assessoria_id)) with check (private.is_treinador(assessoria_id));
create policy preferencias_comunicacao_athlete_select on public.preferencias_comunicacao for select to authenticated using (atleta_id = (select auth.uid()));
create policy preferencias_comunicacao_athlete_optout on public.preferencias_comunicacao for update to authenticated using (atleta_id = (select auth.uid())) with check (atleta_id = (select auth.uid()) and whatsapp_opt_in = false and cobranca_whatsapp = false);
create policy lembretes_cobranca_trainer on public.lembretes_cobranca for all to authenticated using (private.is_treinador(assessoria_id)) with check (private.is_treinador(assessoria_id));
revoke all on public.preferencias_comunicacao, public.lembretes_cobranca from public, anon, authenticated; grant select, insert, update, delete on public.preferencias_comunicacao to authenticated; grant select, insert, update on public.lembretes_cobranca to authenticated;;
